// flow-typed signature: 8a85cd86204f3c5c108df4adda46ebb9
// flow-typed version: <<STUB>>/babel-preset-jest_v^17.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-jest/index' {
  declare module.exports: $Exports<'babel-preset-jest'>;
}
declare module 'babel-preset-jest/index.js' {
  declare module.exports: $Exports<'babel-preset-jest'>;
}
