// flow-typed signature: 7ccd0684c44fa10602c716439c39c246
// flow-typed version: <<STUB>>/babel-preset-babili_vlatest/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-babili'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-babili' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-babili/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-babili/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-babili/lib/index'>;
}
